# Generated by Django 4.2.2 on 2023-10-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heandelmessage", "0003_message_danger_pos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="danger_pos",
            new_name="fire",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sharp",
        ),
    ]
