# Generated by Django 4.2 on 2023-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heandelmessage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='fire',
            new_name='gas',
        ),
        migrations.AddField(
            model_name='message',
            name='humi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='sharp',
            field=models.BooleanField(default=False),
        ),
    ]
